# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'police_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import face_pol
import police_regg

class Ui_Dialog(object):
    
    def cont(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = face_pol.Ui_face_police()
        self.ui.setupUi(self.window) 
        self.window.show()
    
        
    def toadmin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = police_regg.Ui_admin()
        self.ui.setupUi(self.window) 
        self.window.show()
        
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 255)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 83, 611, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(70)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_back = QtWidgets.QLabel(Dialog)
        self.lbl_back.setGeometry(QtCore.QRect(0, 2, 611, 251))
        self.lbl_back.setText("")
        self.lbl_back.setObjectName("lbl_back")
        
        self.btn_next = QtWidgets.QCommandLinkButton(Dialog)
        self.btn_next.setGeometry(QtCore.QRect(520, 210, 51, 41))
        self.btn_next.setObjectName("btn_next")
        self.btn_next.clicked.connect(self.cont)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(50)
        self.btn_next.setFont(font)
        
        self.btn_admin = QtWidgets.QPushButton(Dialog)
        self.btn_admin.setGeometry(QtCore.QRect(0, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Forte")
        self.btn_admin.setFont(font)
        self.btn_admin.setFlat(True)
        self.btn_admin.setObjectName("btn_admin")
        self.btn_admin.clicked.connect(self.toadmin)
        
        self.lbl_back.raise_()
        self.label.raise_()
        self.btn_next.raise_()
        self.btn_admin.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Home"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>FACE RECOGNITION FOR THE NIGERIA POLICE FORCE</p></body></html>"))
        self.btn_next.setText(_translate("Dialog", ""))
        self.btn_admin.setText(_translate("Dialog", "admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
