# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyQts\face_recog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv
from datetime import datetime
import camera
from PyQt5.QtGui import QPixmap 
from camera import *
import cv2

class Ui_Main(object):
    
    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()
    
    def regist(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def create_csv(self):
        today = datetime.date(datetime.now())
        todaystr = str(today)
        filename = '%s.csv'%todaystr
        with open(filename, 'w') as csvfile:
            filewriter = csv.writer(csvfile)
            filewriter.writerow(['Name', 'Time', 'Status'])
        
        self.messagebox('vote', 'successful')
    
    def markAttendance(self):
        try:
            camera.capture()
        except:
            self.messagebox("error", "fatal error")
    
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(592, 259)
        self.createAtt = QtWidgets.QPushButton(Main)
        self.createAtt.setGeometry(QtCore.QRect(15, 210, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.createAtt.setFont(font)
        self.createAtt.setStyleSheet("\n"
"color: rgb(70, 0, 0);")
        self.createAtt.setObjectName("createAtt")
        self.createAtt.clicked.connect(self.create_csv)
        
        self.markAtt = QtWidgets.QPushButton(Main)
        self.markAtt.setGeometry(QtCore.QRect(380, 210, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.markAtt.setFont(font)
        self.markAtt.setStyleSheet("\n"
"color: rgb(70, 0, 0);")
        self.markAtt.setObjectName("markAtt")
        self.markAtt.clicked.connect(self.markAttendance)
        
        self.label = QtWidgets.QLabel(Main)
        self.label.setGeometry(QtCore.QRect(-4, 200, 601, 61))
        self.label.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.backgd = QtWidgets.QLabel(Main)
        self.backgd.setGeometry(QtCore.QRect(0, 0, 591, 201))
        self.backgd.setText("")
        self.backgd.setObjectName("backgd")
        pixmap = QPixmap("voting.jpg")
        self.backgd.setPixmap(pixmap)
        self.backgd.setScaledContents(True)
        
        self.label_2 = QtWidgets.QLabel(Main)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 551, 61))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
    
        
        self.label.raise_()
        self.createAtt.raise_()
        self.markAtt.raise_()
     
        self.backgd.raise_()
        self.label_2.raise_()
       

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.createAtt.setText(_translate("Main", "CREATE VOTING DATABASE"))
        self.markAtt.setText(_translate("Main", "VOTE"))
       
        self.label_2.setText(_translate("Main", "FACE RECOGNITION FOR VOTING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QDialog()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
