# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyQts\vote.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vote(object):
    def setupUi(self, vote):
        vote.setObjectName("vote")
        vote.resize(298, 86)
        self.finish = QtWidgets.QPushButton(vote)
        self.finish.setGeometry(QtCore.QRect(230, 60, 61, 23))
        self.finish.setObjectName("finish")
        self.can1 = QtWidgets.QCheckBox(vote)
        self.can1.setGeometry(QtCore.QRect(10, 20, 81, 17))
        self.can1.setObjectName("can1")
        self.can2 = QtWidgets.QCheckBox(vote)
        self.can2.setGeometry(QtCore.QRect(110, 20, 81, 17))
        self.can2.setObjectName("can2")
        self.can3 = QtWidgets.QCheckBox(vote)
        self.can3.setGeometry(QtCore.QRect(210, 20, 81, 20))
        self.can3.setObjectName("can3")

        self.retranslateUi(vote)
        QtCore.QMetaObject.connectSlotsByName(vote)

    def retranslateUi(self, vote):
        _translate = QtCore.QCoreApplication.translate
        vote.setWindowTitle(_translate("vote", "voting"))
        self.finish.setText(_translate("vote", "FINISH"))
        self.can1.setText(_translate("vote", "Candidate1"))
        self.can2.setText(_translate("vote", "Candidate2"))
        self.can3.setText(_translate("vote", "Candidate3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vote = QtWidgets.QDialog()
    ui = Ui_vote()
    ui.setupUi(vote)
    vote.show()
    sys.exit(app.exec_())
