# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyQts\stud_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from face_algorithm import *

class Ui_Std_front(object):
    
    def cancel(self):
        Std_front.close()
    
    def cont(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_face()
        self.ui.setupUi(self.window) 
        self.window.show()
        Std_front.hide()
        
    
    def setupUi(self, Std_front):
        Std_front.setObjectName("Std_front")
        Std_front.resize(731, 271)
        self.frame = QtWidgets.QFrame(Std_front)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 271))
        self.label.setObjectName("label")
        self.label.setStyleSheet("background-image: url(./myimg/desk_assist.jpg)")
        
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 731, 81))
        self.label_2.setStyleSheet("font: 70 20pt \"Berlin Sans FB Demi\";\n"
                                   "color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(570, 240, 75, 23))
        self.pushButton.setStyleSheet("\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.cont)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 240, 75, 23))
        self.pushButton_2.setStyleSheet("\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.cancel)

        self.retranslateUi(Std_front)
        QtCore.QMetaObject.connectSlotsByName(Std_front)

    def retranslateUi(self, Std_front):
        _translate = QtCore.QCoreApplication.translate
        Std_front.setWindowTitle(_translate("Std_front", "Home"))
        self.label.setText(_translate("Std_front", ""))
        self.label_2.setText(_translate("Std_front", "FACIAL RECOGNITION SYSTEM."))
        self.pushButton.setText(_translate("Std_front", "Continue"))
        self.pushButton_2.setText(_translate("Std_front", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Std_front = QtWidgets.QDialog()
    ui = Ui_Std_front()
    ui.setupUi(Std_front)
    Std_front.show()
    sys.exit(app.exec_())
