# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lbp_img.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication,QWidget, QVBoxLayout, QPushButton, QFileDialog , QLabel, QTextEdit, QMessageBox
from imutils import paths
import numpy as np
import imutils
import cv2
import os
from imgprocess import *
import matplotlib.pyplot as plt
from skimage.io import imread

class Ui_gabo_img(object):
    
    def messages(self, title, message):
        mess = QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QMessageBox.Ok)
        mess.exec_()
   
    
    def browse(self):
        fname = QFileDialog.getOpenFileName()
        self.imagePath = fname[0]
        
        jimread = lambda x: np.expand_dims(imread(x)[::2,::2],0)
        test_imag = jimread(self.imagePath)
      
        plt.imsave('data/input/image.jpg', test_imag[0])
        
        pixmap = QPixmap(self.imagePath)
        self.lbl_img.setPixmap(QPixmap(pixmap))
        self.lbl_img.setScaledContents(True)
        print(self.imagePath)

        file = open("imgpath.txt", "w")
        file.write(self.imagePath)
        file.close()
    
    def detect(self):
        INPUT_DIR = 'data/input'
        for filename in os.listdir(INPUT_DIR):
            res = get_objects_from_file(filename, False)
            
    
    def setupUi(self, gabo_img):
        gabo_img.setObjectName("gabo_img")
        gabo_img.resize(400, 202)
        self.lbl_back = QtWidgets.QLabel(gabo_img)
        self.lbl_back.setGeometry(QtCore.QRect(0, 0, 401, 201))
        self.lbl_back.setObjectName("lbl_back")
        self.lbl_img = QtWidgets.QLabel(gabo_img)
        self.lbl_img.setGeometry(QtCore.QRect(10, 10, 181, 151))
        self.lbl_img.setObjectName("lbl_img")
        
        self.btn_browse = QtWidgets.QPushButton(gabo_img)
        self.btn_browse.setGeometry(QtCore.QRect(10, 170, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_browse.setFont(font)
        self.btn_browse.setObjectName("btn_browse")
        self.btn_browse.clicked.connect(self.browse)
        
        self.pushButton = QtWidgets.QPushButton(gabo_img)
        self.pushButton.setGeometry(QtCore.QRect(230, 50, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.detect)

        self.retranslateUi(gabo_img)
        QtCore.QMetaObject.connectSlotsByName(gabo_img)

    def retranslateUi(self, gabo_img):
        _translate = QtCore.QCoreApplication.translate
        gabo_img.setWindowTitle(_translate("gabo_img", "face"))
        self.lbl_back.setText(_translate("gabo_img", ""))
        self.lbl_img.setText(_translate("gabo_img", ""))
        self.btn_browse.setText(_translate("gabo_img", "BROWSE"))
        self.pushButton.setText(_translate("gabo_img", "DETECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gabo_img = QtWidgets.QDialog()
    ui = Ui_gabo_img()
    ui.setupUi(gabo_img)
    gabo_img.show()
    sys.exit(app.exec_())
